theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
#rulers = [80]
shell = ["zsh", "-c"]

[editor.statusline]
left = ["mode", "diagnostics"]
center = ["file-name"]
right = ["selections", "file-type", "file-encoding", "position-percentage", "position"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
tab = "completion"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
